update by safar
afifnandya/hrd-frontend pull request #9
Opened 2022-12-30 08:38 UTC by safarilkom7

2023-01-02 08:07 UTC, afif-hh requested changes

2023-01-02 08:07 UTC, afif-hh commented on src/api/master/createArea.ts
> +import axios from 'axios'
jgn panggil dari axios langsung, tapi dari 'composable/useAxios'

2023-01-02 08:07 UTC, afif-hh commented on src/api/master/createArea.ts
> +export async function CreateArea(payload: CreateAreaPayload) {
`c` nya kecil, kita pakai standar camelCase mas

2023-01-02 08:07 UTC, afif-hh commented on src/api/master/createDepartment.ts
> +import axios from 'axios'
jgn panggil dari axios langsung, tapi dari 'composable/useAxios'

2023-01-02 08:07 UTC, afif-hh commented on src/api/master/createDepartment.ts
> +export async function CreateDepartment(payload: CreateDepartmentPayload) {
c kecil

2023-01-02 08:07 UTC, afif-hh commented on src/api/master/createDepartment.ts
> +import axios from 'axios'
isAxios erorr ada di composable juga

2023-01-02 09:02 UTC, safarilkom7 commented on src/api/master/createArea.ts
> +import axios from 'axios'
ok mas, makasih.

2023-01-02 09:02 UTC, safarilkom7 commented on src/api/master/createArea.ts
> +export async function CreateArea(payload: CreateAreaPayload) {
siap mas

2023-01-07 12:09 UTC, safarilkom7 reviewed
ok mas

2023-01-08 15:01 UTC, afif-hh approved these changes

2023-01-08 15:03 UTC, merged